version: '3'

services:
  backend:
    build: './fr-administration'
    ports:
      - "3000:3000"  # Port du conteneur backend
    networks:
      - my-net
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_PORT: 3306

  frontend:
    build: './fr-administration-front'
    ports:
      - "8080:80"  # Port du conteneur frontend
    networks:
      - my-net


  mariadb:
    networks:
      - my-net
    image: mariadb
    volumes:
      - mydatabase:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: mydatabase

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    networks:
#      - my-net
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    links:
#      - backend
#      - frontend



volumes:
  mydatabase:


networks:
  my-net:
    external: true

