version: '3'

services:
  backend:
    build: './fr-administration'
#    ports:
#      - "3000:3000"  # Port du conteneur backend
    networks:
      - my-net
      - notification
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_PORT: 3306
      RABBITMQ_USER: myuser
      RABBITMQ_PASS: mypassword
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_QUEUE: myQueue

  frontend:
    build: './fr-administration-front'
    ports:
      - "8080:80"  # Ports du conteneur frontend
    networks:
      - my-net


  mariadb:
    networks:
      - my-net
    image: mariadb
    volumes:
      - mydatabase:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: mydatabase

  nginx:
    image: nginx:latest
    networks:
      - my-net
    container_name: nginx-proxy
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  rabbitMQ:
    image: rabbitmq:3.13-rc-management
    networks:
      - notification
    ports:
      - "3307:3307"
      - 5672:5672
      - 15672:15672
    container_name: Rabbit
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword

volumes:
  mydatabase:


networks:
  my-net:
    external: false
  notification:
    external: false

